/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/layouts/navigation/NavigationPCMenu1 copy.vue')['default']
    MainLayout: typeof import('./src/layouts/MainLayout.vue')['default']
    NavigationItem: typeof import('./src/layouts/navigation/NavigationItem.vue')['default']
    NavigationLogo: typeof import('./src/layouts/navigation/NavigationLogo.vue')['default']
    NavigationMenu1: typeof import('./src/layouts/navigation/NavigationMenu1.vue')['default']
    NavigationMobileMenu: typeof import('./src/layouts/navigation/NavigationMobileMenu.vue')['default']
    NavigationMobileMenu1: typeof import('./src/layouts/navigation/NavigationMobileMenu1.vue')['default']
    NavigationPCMenu: typeof import('./src/layouts/navigation/NavigationPCMenu.vue')['default']
    NavigationPCMenu1: typeof import('./src/layouts/navigation/NavigationPCMenu1.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheContainer: typeof import('./src/layouts/container/TheContainer.vue')['default']
    TheFooter: typeof import('./src/layouts/TheFooter.vue')['default']
    TheNavigation: typeof import('./src/layouts/navigation/TheNavigation.vue')['default']
  }
}
